version: "3"

tasks:
    run:
        desc: Run docker first then start the browser
        cmds:
            - "sudo docker compose up --build -d"
            - "sleep 2"
            - "./app/dev/open-browser"