version: "3"

tasks:
    run:
        desc: Run docker first then start the browser
        cmds:
            - |
               cd app/dev/
               go build open-browser.go
               ./open-browser