name: Deploy to SFTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Echo Secrets
          run: |
            echo "FTP_SERVER: ${{ secrets.FTP_SERVER }}"
            echo "FTP_PORT: ${{ secrets.FTP_PORT }}"
            echo "FTP_USERNAME: ${{ secrets.FTP_USERNAME }}"
            echo "FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}"

        - name: deploy
          uses: pressidium/lftp-mirror-action@v1
          with:
            host: ${{ secrets.FTP_SERVER }}
            port: ${{ secrets.FTP_PORT }}
            user: ${{ secrets.FTP_USERNAME }}
            pass: ${{ secrets.FTP_PASSWORD }}
            localDir: './app/*'
            remoteDir: '/home/container/'
            reverse: true
