name: Deploy to SFTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Debug
          run: |
            env
            printenv
            echo "Secrets: ${{ toJson(secrets) }}"

        - name: deploy
          uses: pressidium/lftp-mirror-action@v1
          with:
            host: ${{ sftp-deploy.secrets.FTP_SERVER }}
            port: ${{ sftp-deploy.secrets.FTP_PORT }}
            user: ${{ sftp-deploy.secrets.FTP_USERNAME }}
            pass: ${{ sftp-deploy.secrets.FTP_PASSWORD }}
            localDir: './app/*'
            remoteDir: '/home/container/'
            reverse: true
          
          
